[[constraint]]
  name = "github.com/pulumi/pulumi"
  branch = "master"

[[constraint]]
  name = "github.com/pulumi/pulumi-terraform"
  branch = "master"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  source = "github.com/Frassle/terraform-provider-openstack"
  branch = "pulumi-master"
