[[override]]
  name = "github.com/pulumi/pulumi"
  version = "v0.14.0-rc1"

[[override]]
  name = "github.com/pulumi/pulumi-terraform"
  version = "v0.14.0-rc1"

[[override]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  source = "github.com/Frassle/terraform-provider-openstack"
  branch = "pulumi-master"
