// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Linq;

namespace Pulumi.Openstack.Compute {

	/// <summary>
	/// A collection of arguments for invoking getKeypair.
	/// </summary>
	public struct GetKeypairArgs {
		/// <summary>
		/// The unique name of the keypair.
		/// </summary>
		public string Name { get; set; }

		/// <summary>
		/// The region in which to obtain the V2 Compute client.
		/// If omitted, the `region` argument of the provider is used.
		/// </summary>
		public string Region { get; set; }

	} // GetKeypairArgs

	/// <summary>
	/// A collection of values returned by getKeypair.
	/// </summary>
	public struct GetKeypairResult {
		/// <summary>
		/// The OpenSSH-formatted public key of the keypair.
		/// </summary>
		public string PublicKey { get; set; }

		/// <summary>
		/// See Argument Reference above.
		/// </summary>
		public string Region { get; set; }

		/// <summary>
		/// id is the provider-assigned unique ID for this managed resource.
		/// </summary>
		public string Id { get; set; }

	} // GetKeypairResult

	public static partial class ComputeModule {
		/// <summary>
		/// Use this data source to get the ID and public key of an OpenStack keypair.
		/// </summary>
		public static System.Threading.Tasks.Task<GetKeypairResult> GetKeypair(GetKeypairArgs args, Pulumi.InvokeOptions opts = default(Pulumi.InvokeOptions)) {
			var invokeArgs = new Google.Protobuf.WellKnownTypes.Struct();
			invokeArgs.Fields["name"] = Protobuf.ToProtobuf(args.Name);
			invokeArgs.Fields["region"] = Protobuf.ToProtobuf(args.Region);

			var task = Pulumi.Runtime.InvokeAsync("openstack:compute/getKeypair:getKeypair", invokeArgs, opts);

			return task.ContinueWith(response => {
				var protobuf = response.Result;
				var result = new GetKeypairResult();
				if (protobuf.Fields.ContainsKey("publicKey")) {
					result.PublicKey = Protobuf.ToString(protobuf.Fields["publicKey"]);
				}
				if (protobuf.Fields.ContainsKey("region")) {
					result.Region = Protobuf.ToString(protobuf.Fields["region"]);
				}
				if (protobuf.Fields.ContainsKey("id")) {
					result.Id = Protobuf.ToString(protobuf.Fields["id"]);
				}
				return result;
			});
		} // GetKeypair

	} // ComputeModule
} // Pulumi.Openstack.Compute
